language: node_js
node_js:
  - 10
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAT5HW7TSQAUTCS243
  secret_access_key:
    secure: FWZxmORUVoQnDEOs7LDEvYDW0OrqYJBjVt++qaDNq9B+5tPMnPrNAMSfaFJK3WW9lHXVtbCeupiXLWaI7BVK1TqPP5Ms2lkYgHFx5kaGV3h7TvCxZpi0D+SQQ2ec80Ymtr9cM0zNsRgG6TEExZQQCtEqEfPPzv+C9cPr3K4jiyMxhS6H9nZVppDD7G3HQQPeNT+0UPa6kOxKsFg25LKoyN2W54GFxteei1TzzcK7iMvl3HjyXGfNMA8nOoM1jvgGurCjbqmnwniX1DDGKWdviIKWQ7Per7+NDUqCgekWd5gxTP6Dsn/PGxIlI4PmAfEmpjx8ivyLNclJw7OeDpNkFKkzeiIZzinUDSS5IK30AOOXCdsTQ4A107WYLBEEYtE8r87evlwHMXUS1V7QNZudBFFjtA+DczwwEELIXdqUseXXTxsLfyz/CPJhyKGl2gnKQ0469ll4/BSyRD6TUvSADUnKhbbnmcrVUL/hi/393Cpq0j0lY5cHoU9Ch68164K0nEWR6nU5Evaw1MDl6r3NEFb3/M1ny+elwt5nGRkRikLhulbA92xjDL4SzVRIPj4Bbv6c+FB204ReVZqd5PkL0MlFqEJTXJ33D/xTHk/kpIo3iO0XrDGQJ8F1sz5ZumwIkrOCTzzqB1p2jkG+GdVDkUDVcUto4ZBlnhDKeAtJQ1Q=
  bucket: "stephencookdev.co.uk"
  skip_cleanup: true
  region: eu-west-1
  local_dir: __sapper__/export
  upload-dir: test
  on:
    branch: master
