language: node_js
node_js:
  - 10
script:
  - mkdir -p __sapper__/export
  - npm run build-prod
install:
  - npm config set registry https://npm.pkg.github.com/stephencookdev
  - echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
  - npm install
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  bucket: "stephencook.dev"
  skip_cleanup: true
  region: eu-west-1
  local_dir: __sapper__/export
  on:
    branch: master
after_deploy:
  - npm run deploy-invalidate-cloudfront
